config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'pages/info'

  root 'good_times#index'
  resources :good_times

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :good_time
end

app/models/good_time.rb
class GoodTime < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :good_time_id)
    end
end

app/controllers/good_times_controller.rb
class GoodTimesController < ApplicationController
  before_action :set_good_time, only: [:show, :edit, :update, :destroy]

  # GET /good_times
  # GET /good_times.json
  def index
    @good_times = GoodTime.all
  end

  # GET /good_times/1
  # GET /good_times/1.json
  def show
    @comments = @good_time.comments.all
    @comment = @good_time.comments.build
  end

  # GET /good_times/new
  def new
    @good_time = GoodTime.new
  end

  # GET /good_times/1/edit
  def edit
  end

  # POST /good_times
  # POST /good_times.json
  def create
    @good_time = GoodTime.new(good_time_params)

    respond_to do |format|
      if @good_time.save
        format.html { redirect_to @good_time, notice: 'Good time was successfully created.' }
        format.json { render :show, status: :created, location: @good_time }
      else
        format.html { render :new }
        format.json { render json: @good_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /good_times/1
  # PATCH/PUT /good_times/1.json
  def update
    respond_to do |format|
      if @good_time.update(good_time_params)
        format.html { redirect_to @good_time, notice: 'Good time was successfully updated.' }
        format.json { render :show, status: :ok, location: @good_time }
      else
        format.html { render :edit }
        format.json { render json: @good_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /good_times/1
  # DELETE /good_times/1.json
  def destroy
    @good_time.destroy
    respond_to do |format|
      format.html { redirect_to good_times_url, notice: 'Good time was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_good_time
      @good_time = GoodTime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def good_time_params
      params.require(:good_time).permit(:name, :description, :picture, :visit)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/good_times_helper.rb
module GoodTimesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <%= f.hidden_field :good_time_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Good time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.good_time_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Good time:</strong>
  <%= @comment.good_time_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/good_times/_form.html.erb
<%= form_for(@good_time) do |f| %>
  <% if @good_time.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@good_time.errors.count, "error") %> prohibited this good_time from being saved:</h2>

      <ul>
      <% @good_time.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :visit %><br>
    <%= f.date_select :visit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/good_times/edit.html.erb
<h1>Editing Good Time</h1>

<%= render 'form' %>

<%= link_to 'Show', @good_time %> |
<%= link_to 'Back', good_times_path %>

app/views/good_times/index.html.erb
<h1>Good Times in LA!!!</h1>

<% @good_times.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |good_time| %>
      <div class="col-md-4">
        <%= image_tag good_time.picture_url, width: '100%' if good_time.picture.present?%>
        <h4><%= link_to good_time.name, good_time %></h4>
        <%= good_time.description %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/good_times/new.html.erb
<h1>Good Time</h1>

<%= render 'form' %>

<%= link_to 'Back', good_times_path %>

app/views/good_times/show.html.erb
<p id="notice"><%= notice %></p>

<div class='row'>
  <div class="col-md-9">
    <%= image_tag(@good_time.picture_url, width: '100%') if @good_time.picture.present? %>
    <h3><Comments></h3>
    <% @comments.each do |comment| %>
      <div>
        <strong><%= comment.user_name %></strong>
        <br />
        <p><%= comment.body %></p>
        <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
      </div>
    <% end %>
      <%= render 'comments/form' %>
  </div>

  <div class="col-md-3">
    <p><b>Name: </b><%= @good_time.name %></p>
    <p><b>Description: </b><%= @good_time.description %></p>
    <p>
      <%= link_to 'Edit', edit_good_time_path(@good_time) %> |
      <%= link_to 'Destroy', @good_time, data: { confirm: 'Are you sure?' }, method: :delete %> |
      <%= link_to 'Back', good_time_path %>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodTimesLa</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= yield %>
  </div>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Good Times in LA</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/good_times">Good Times</a></li>
          <li ><%= link_to "Create a Good Time", new_good_time_path %></li>
          <li ><%= link_to "Info", pages_info_path %></li>
        </ul>
      </div>
    </div>
  </nav>
  <footer>
    <div class="container">
      Rails Girls 2015
    </div>
  </footer>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</body>
</html>

app/views/pages/info.html.erb
<h1>Why is this helpful?</h1>
<p>This websites goal is to help LA newbies find new and exciting activities in LA.</p>